### ISSUE TITLE
Error on Apple Silicon: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by abegehr** [invertase/firestore-ios-sdk-frameworks#51] opened 2022-05-15 14:52 UTC
I'm facing `Undefined symbol` errors when trying to build and run a flutter app with the precompiled FirebaseFirestore pod installed on an Apple Silicon MBP.
When I remove `pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.15.0'` from the Podfile, it builds and runs as expected (though way slower 😅).
– Should the pre-compiled FirebaseFirestore pod support developing on Apple silicon?

Build log on simulator:

```
Launching lib/main.dart on iPhone 13 in debug mode...
lib/main.dart:1
Xcode build done.                                            8.9s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[39167]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1da775eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10482c4f8). One of the two will be used. Which one is undefined.
    objc[39167]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1da775f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10482c548). One of the two will be used. Which one is undefined.
    objc[39167]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1da775f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10482c598). One of the two will be used. Which one is undefined.
    objc[39167]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1da775fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10482c5e8). One of the two will be used. Which one is undefined.
    objc[39167]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1da775ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10482c638). One of the two will be used. Which one is undefined.
    objc[39167]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1da776040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10482c688). One of the two will be used. Which one is undefined.
    2022-05-15 23:21:19.567 xcodebuild[39167:150152] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-05-15 23:21:19.568 xcodebuild[39167:150152] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/gc/f02630rs7h1c1wpw8883cn9j086l3v/T/flutter_tools.Pa1sv0/flutter_ios_build_temp_dirW41kxN/temporary_xcresult_bundle
    Undefined symbols for architecture arm64:
      "leveldb::WriteBatch::WriteBatch()", referenced from:
          firebase::firestore::local::LevelDbTransaction::Commit() in FirebaseFirestore(leveldb_transaction.o)
      "leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)", referenced from:
          firebase::firestore::local::LevelDbTransaction::Commit() in FirebaseFirestore(leveldb_transaction.o)
      "leveldb::WriteBatch::~WriteBatch()", referenced from:
          firebase::firestore::local::LevelDbTransaction::Commit() in FirebaseFirestore(leveldb_transaction.o)
      "leveldb::Status::Status(leveldb::Status::Code, leveldb::Slice const&, leveldb::Slice const&)", referenced from:
          firebase::firestore::local::LevelDbTransaction::Get(absl::lts_20211102::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in FirebaseFirestore(leveldb_transaction.o)
      "leveldb::Options::Options()", referenced from:
          firebase::firestore::local::LevelDbPersistence::OpenDb(firebase::firestore::util::Path const&) in FirebaseFirestore(leveldb_persistence.o)
      "leveldb::WriteBatch::Delete(leveldb::Slice const&)", referenced from:
          firebase::firestore::local::LevelDbTransaction::Commit() in FirebaseFirestore(leveldb_transaction.o)
      "leveldb::Status::ToString() const", referenced from:
          firebase::firestore::local::ConvertStatus(leveldb::Status const&) in FirebaseFirestore(leveldb_util.o)
          firebase::firestore::local::LevelDbMigrations::ReadSchemaVersion(leveldb::DB*) in FirebaseFirestore(leveldb_migrations.o)
          firebase::firestore::local::LevelDbTransaction::Iterator::Seek(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in FirebaseFirestore(leveldb_transaction.o)
          firebase::firestore::local::LevelDbTransaction::Iterator::AdvanceLDB() in FirebaseFirestore(leveldb_transaction.o)
          firebase::firestore::local::LevelDbTransaction::Commit() in FirebaseFirestore(leveldb_transaction.o)
          firebase::firestore::local::LevelDbMutationQueue::LookupMutationBatch(int) in FirebaseFirestore(leveldb_mutation_queue.o)
          firebase::firestore::local::LevelDbRemoteDocumentCache::Get(firebase::firestore::model::DocumentKey const&) in FirebaseFirestore(leveldb_remote_document_cache.o)
          ...
      "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
          firebase::firestore::local::LevelDbPersistence::OpenDb(firebase::firestore::util::Path const&) in FirebaseFirestore(leveldb_persistence.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/gc/f02630rs7h1c1wpw8883cn9j086l3v/T/flutter_tools.Pa1sv0/flutter_ios_build_temp_dirW41kxN/temporary_xcresult_bundle
Error (Xcode): Undefined symbol: leveldb::WriteBatch::WriteBatch()

Error (Xcode): Undefined symbol: leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)

Error (Xcode): Undefined symbol: leveldb::WriteBatch::~WriteBatch()

Error (Xcode): Undefined symbol: leveldb::Status::Status(leveldb::Status::Code, leveldb::Slice const&, leveldb::Slice const&)

Error (Xcode): Undefined symbol: leveldb::Options::Options()

Error (Xcode): Undefined symbol: leveldb::WriteBatch::Delete(leveldb::Slice const&)

Error (Xcode): Undefined symbol: leveldb::Status::ToString() const

Error (Xcode): Undefined symbol: leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)

Could not build the application for the simulator.
Error launching application on iPhone 13.
Exited
```

Flutter doctor:

```
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/abegehr/retention_folder/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • iPhone 13 (mobile)      • AC26429D-AE91-4E0F-AF60-83404CEE5BF9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
exit code 0
```

Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.15.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end

    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by mikehardy** [comment] 2022-05-15 15:13
Hmm - it's supposed to work, I'm not aware of anything specific for arm64, failure wise, we've heard no other reports and I use an arm64 machine from time to time.

Let me confirm it's supposed to be working, in the meantime, there is also a more global "let's speed up Xcode builds" solution you can apply using ccache (available from brew). I recognize you're a flutter developer but I haven't written it up specifically for flutter, I just recently collaborated with the react-native team to document how we (Invertase, via my CI work) do it here though and you can see all the steps - which should apply equally to flutter - https://reactnative.dev/docs/build-speed#local-caches

For your specific issue, I wonder if it is not detecting that you need leveldb for some reason? This was the source of a *lot* of trouble for me and I'm still not satisfied fully with the outcome

Witness: https://github.com/invertase/firestore-ios-sdk-frameworks/pulls?q=is%3Apr+leveldb

https://github.com/invertase/firestore-ios-sdk-frameworks/issues/2#issuecomment-746894897


You might try:

https://github.com/invertase/firestore-ios-sdk-frameworks#resolving-leveldb-missing-or-duplicate-symbol-errors


> If your build fails due with missing 'leveldb' symbols, pod FirebaseFirestore/WithLeveldb as the pod name instead of pod FirebaseFirestore, reinstall pods and try rebuilding.

**Comment by dpa99c** [comment] 2022-05-31 10:09
[Anecdotal evidence from users of my plugin](https://github.com/dpa99c/cordova-plugin-firebasex/issues/735) that there may be an issue with Apple Silicon after updating from v8.11.0 to v9.1.0

**Comment by mikehardy** [comment] 2022-05-31 11:33
Thanks for the extra context, I'll check this on an m1 machine today

**Comment by suejinv** [comment] 2022-06-03 08:14
I'm having a similar problem with @dpa99c.
The following error occurs when building on the device.

Error 
`error: no such module 'FirebaseFirestore'`

Warning
```
warning: [CP] FirebaseFirestore.xcframework: Unable to find matching slice in 'ios-arm64_x86_64-simulator ios-arm64 ios-arm64_x86_64-maccatalyst' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] gRPC-Core.xcframework: Unable to find matching slice in 'ios-arm64 ios-arm64_x86_64-simulator ios-arm64_x86_64-maccatalyst' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] Libuv-gRPC.xcframework: Unable to find matching slice in 'ios-arm64_x86_64-maccatalyst ios-arm64_x86_64-simulator ios-arm64' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] gRPC-C++.xcframework: Unable to find matching slice in 'ios-arm64 ios-arm64_x86_64-maccatalyst ios-arm64_x86_64-simulator' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] BoringSSL-GRPC.xcframework: Unable to find matching slice in 'ios-arm64 ios-arm64_x86_64-maccatalyst ios-arm64_x86_64-simulator' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] FirebaseFirestoreSwift.xcframework: Unable to find matching slice in 'ios-arm64 ios-arm64_x86_64-simulator ios-arm64_x86_64-maccatalyst' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] abseil.xcframework: Unable to find matching slice in 'ios-arm64_x86_64-simulator ios-arm64_x86_64-maccatalyst ios-arm64' for the current build architectures (arm64 armv7) and platform (-iphoneos).
warning: [CP] leveldb-library.xcframework: Unable to find matching slice in 'ios-arm64 ios-arm64_x86_64-maccatalyst ios-arm64_x86_64-simulator' for the current build architectures (arm64 armv7) and platform (-iphoneos).
```

One thing is confirmed, it succeeds or fails depending on the project option value.

<img width="743" alt="스크린샷 2022-06-03 오후 5 09 10" src="https://user-images.githubusercontent.com/5172702/171815535-231d3ac2-0d0c-40b0-a6e6-acb2ddafad38.png">

- `Build Active Architecture Only = Yes` > Build Success
- `Build Active Architecture Only = No` > Build Fail

I hope it helps to figure out the cause.

**Comment by mikehardy** [comment] 2022-06-03 13:27
I exclude those things in typyical builds, personally, I use this stanza in my automated reproductions:

https://github.com/mikehardy/rnfbdemo/blob/51ef9f125d67b599854de81764b9451514a5608e/make-demo.sh#L193-L195

Which generates something like in the post_install block of Podfile

https://github.com/invertase/react-native-firebase/blob/ee740f80501fdd2ea5184515c4840340fca55e63/tests/ios/Podfile#L49-L58

```ruby
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          # Arch selection is needed to work across M1/Intel macs, became necessary when App Check was added
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
          config.build_settings['EXCLUDED_ARCHS'] = 'i386'
        end
      end
      aggregate_target.user_project.save
    end
```

This is one of things I file away in the "wow, Xcode is irritating to work with" category. Curious if it helps anyone else

**Comment by pinguluk** [comment] 2022-06-07 11:45
> [Anecdotal evidence from users of my plugin](https://github.com/dpa99c/cordova-plugin-firebasex/issues/735) that there may be an issue with Apple Silicon after updating from v8.11.0 to v9.1.0

I confirm I have the same issue.
I fixed by using this https://github.com/dpa99c/cordova-plugin-firebasex/issues/735#issuecomment-1140775999
I've tried this method too https://github.com/dpa99c/cordova-plugin-firebasex/issues/735#issuecomment-1141900552, got this result https://github.com/dpa99c/cordova-plugin-firebasex/issues/735#issuecomment-1148536526

**Comment by mikehardy** [comment] 2022-06-14 12:47
Sorry for the delay, and apologies that this is not 100% on target yet, but I am working to forward port react-native-firebase to firebase-ios-sdk v9.1.0 and while we normally don't use this precompiled version of the framework in our code, I can assert that when I turn it on, it works fine on my M1 machine.

So I do not think there is a general problem with the precompiled artifact, there must be something more subtle at play.

All our work on the react-native-firebase module is open, repro is via our e2e harness which may be run like so https://github.com/invertase/react-native-firebase/blob/main/tests/README.md and my repro branch showing success is pushed here at the moment https://github.com/invertase/react-native-firebase/tree/%40mikehardy/firestore-ios-frameworks-v9-repro

I haven't done a reproduction with FlutterFire in a while however I will note that they use the precompiled framework:
https://github.com/firebase/flutterfire/blob/2854cbcb5a2e604ace8dc55993893e5ffdbff5a8/packages/cloud_firestore/cloud_firestore/example/macos/Podfile#L53
https://github.com/firebase/flutterfire/blob/2854cbcb5a2e604ace8dc55993893e5ffdbff5a8/packages/cloud_firestore/cloud_firestore/example/ios/Podfile#L54

...just still on v8 at the moment https://github.com/firebase/flutterfire/blob/2854cbcb5a2e604ace8dc55993893e5ffdbff5a8/packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb#L3

so as soon as they forward-port to firebase-ios-sdk v9 it will either show up - confirming this issue - or it will not show up and we will be 2/2 on "works for us" 🤔 . I've asked around to see if anyone else has pursued this forward-port effort and might be able to take it up if not.

**Comment by mikehardy** [comment] 2022-06-27 15:23
My LevelDB sub-specs should help with this, unfortunately I do not think it is actionable otherwise.
After releasing react-native-firebase v15 last week and working through user upgrade issues I had a chance to come back around here and test using this optimization in our test app, it works fine and I confirm I was definitely using it:

```

[mike@yv ~/work/Invertase/react-native-firebase (main *)]$ cat tests/ios/Podfile.lock |grep FirebaseFirestore
    - FirebaseFirestore (~> 9.2.0)
  - FirebaseFirestore (9.2.0):
    - FirebaseFirestore/AutodetectLeveldb (= 9.2.0)
  - FirebaseFirestore/AutodetectLeveldb (9.2.0):
    - FirebaseFirestore/Base
  - FirebaseFirestore/Base (9.2.0)
  - FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `9.2.0`)
  FirebaseFirestore:
  FirebaseFirestore:
  FirebaseFirestore: 4e108dcc1385ab5d596d630f2d28a4dfcaad04fe
```

With regret that I cannot reproduce and thus solve everyone's issues, I don't think there is anything wrong with this particular distribution

**Closed by mikehardy** 2022-06-27 15:23 UTC
Labels: bug, help wanted

**Comment by TiBz0u** [comment] 2022-11-09 15:10
> I'm unable to reproduce this on my M1 machine.
> 
> I think there are two issues. I think the original poster had issues with the podspec's detection of leveldb, and should be able to resolve it using one of the less-automatic / more-certain methods of reference.
> 
> @dpa99c I think your problem is different - the biggest change between v8 and v9, in my opinion was this: you must `use_frameworks!` in your podfile now. Perhaps that is the problem? Also some of the header files moved around.
> 
> I have not landed the PR for react-native-firebase to use firebase-ios-sdk v9+ yet as I'm still collaborating with the apple sdk team on a couple details, but you may examine my forward port efforts here to see what we had to change:
> 
> https://github.com/invertase/react-native-firebase/pull/6274/files
> 
> Most of the diff noise is testing stuff these two commits are the real effort, small, but important
> 
> [invertase/react-native-firebase@0b752ac#diff-52fbdf0dbe18205cd99cd87fe80e020b32bb8b7cbf8234bd65e8b6fcd9d804eb](https://github.com/invertase/react-native-firebase/commit/0b752acbe02034175ae310f33c71e5ae69caba7f#diff-52fbdf0dbe18205cd99cd87fe80e020b32bb8b7cbf8234bd65e8b6fcd9d804eb)
> 
> [invertase/react-native-firebase@6832782](https://github.com/invertase/react-native-firebase/commit/68327826717ec8102afe08a48d84e6e3fe96a4e5)
> 
> We already had static framework in our react-native-firebase podspecs, you may be interested in how we link based on the Podfile variable consuming libraries may set:
> 
> https://github.com/invertase/react-native-firebase/blob/ee740f80501fdd2ea5184515c4840340fca55e63/packages/app/RNFBApp.podspec#L33-L38
> 
> https://github.com/invertase/react-native-firebase/blob/ee740f80501fdd2ea5184515c4840340fca55e63/packages/firestore/RNFBFirestore.podspec#L39-L44
> 
> That's a lot of extra information for you to hopefully get moving, for me - with no reproduction I have no action here. I believe it is working fine on M1, both firebase-ios-sdk v8 and v9

The configuration of the cordova Plugin developed by @dpa99c seems to be correctly configured for `use_framework!`

Here is the generated PodFile. @mikehardy Can you confirm it's ok?
`source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'My Application' do
	project 'My Application.xcodeproj'
	pod 'Firebase/Core', '9.1.0'
	pod 'Firebase/Auth', '9.1.0'
	pod 'Firebase/Messaging', '9.1.0'
	pod 'Firebase/Performance', '9.1.0'
	pod 'Firebase/RemoteConfig', '9.1.0'
	pod 'Firebase/InAppMessaging', '9.1.0'
        pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.1.0'
	pod 'Firebase/Crashlytics', '9.1.0'
	pod 'Firebase/Functions', '9.1.0'
	pod 'Firebase/Installations', '9.1.0'
	pod 'GoogleSignIn', '6.2.1'
end`

**Comment by mikehardy** [comment] 2022-11-09 15:17
I cannot confirm it is okay, I do not use cordova. It seems correct but I won't offer false comfort on something I don't personally use, you'll have to test it and see, and that is confirmation.

I can confirm that firebase-ios-sdk v9 is old and likely not compatible with current iOS versions.
v10.1.0 is current.

**Comment by TiBz0u** [comment] 2022-11-09 16:07
Hi @mikehardy , thanks for your quick answer. I was only asking for a podfile configuration check. Maybe you can detect a missing parameter/option.
We'll give a shot with the v10.
