### ISSUE TITLE
Known Issue: Build failure when used with Firebase RTDB

### ISSUE THREAD

**Issue by Salakar** [invertase/firestore-ios-sdk-frameworks#2] opened 2020-06-12 17:38 UTC
Looks like if you're using Firebase Realtime Database within the same project you may experience `duplicate symbol` build failures relating to `leveldb` as both of these depend on it.

![image-1](https://user-images.githubusercontent.com/5347038/84531029-d33c9680-acdb-11ea-9311-f7d010db71c7.png)

**Comment by ahanusek** [comment] 2020-06-18 10:33
@Salakar But this PR is only merged to master and tag 6.27.0. Shouldn't we make rebase from master onto other tags (6.25.0 for RN i.e)?

**Comment by Salakar** [comment] 2020-06-18 12:04
Unfortunately I can't back port them without resetting git and force pushing as the tags have already been made (if I do this it'll cause issues with anyone using the tags previously as the commit shas would no longer match up)

Having said that though; RNFB supports 6.27.0 also, can override the version it uses by adding a line to your podfile, see: https://rnfirebase.io/#ios

```ruby
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.27.0'
```

**Comment by ahanusek** [comment] 2020-06-18 12:23
Oh, I see, thanks very much ;)

**Comment by ahanusek** [comment] 2020-10-01 12:02
I don't know why now this condition doesn't work properly in my repo:

```
 skip_leveldb = false

  # FlutterFire
  if current_definition_string.include?('firebase_database')
    skip_leveldb = true
  # React native Firebase  
  elsif current_definition_string.include?('RNFBDatabase')
    skip_leveldb = true
  # Pod spec used directly  
  elsif current_definition_string.include?('FirebaseDatabase')
    skip_leveldb = true
  # Umbrella pod spec  
  elsif current_definition_string.include?('Firebase/Database')
    skip_leveldb = true
  end

  if skip_leveldb
    s.exclude_files = 'FirebaseFirestore/leveldb-library.xcframework'
  end
``` 

I have database and firestore dependencies and using this precompiled package and still getting this error because this condition doesn't work and leveldb is duplicated in my Pods folder.

```
 pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.30.0'
```

```
    "@react-native-firebase/analytics": "7.6.1",
    "@react-native-firebase/app": "8.4.1",
    "@react-native-firebase/auth": "9.2.1",
    "@react-native-firebase/crashlytics": "8.4.2",
    "@react-native-firebase/database": "7.5.5",
    "@react-native-firebase/dynamic-links": "7.5.2",
    "@react-native-firebase/firestore": "7.8.0",
    "@react-native-firebase/functions": "7.4.2",
    "@react-native-firebase/messaging": "7.8.4",
    "@react-native-firebase/perf": "^7.4.2",
    "@react-native-firebase/storage": "7.4.2",
```

**Comment by mikehardy** [comment] 2020-10-01 13:10
I have this problem as well, it's something to do with leveldb not being detected correctly, and I haven't found the root cause but had to disable this optimization for the demo project I toss out to people in support of react-native-firebase: https://github.com/mikehardy/rnfbdemo/blob/fc7e943ca95fe1777300985f31db2a075d2da4a5/make-demo.sh#L44-L61

**Comment by jhubbardsf** [comment] 2020-12-16 19:38
Getting the same thing as you mike.

`  "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
          firebase::firestore::local::LevelDbPersistence::OpenDb(firebase::firestore::util::Path const&) in FirebaseFirestore(leveldb_persistence.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by jhubbardsf** [comment] 2020-12-16 20:57
I'm not sure if this was the same issue that mike was seeing or not. Here was my fix/workaround.

I forked this repository and looked at the leveldb-library.xcframewor/info.plist file. Under the armv7_arm64 dict, I switched the array around so that arm64 cam ebefore armv7. I noticed they do this in later versions, presumedly for this reason. I pushed that to my fork as the same tag and everything builds great. Granted I only made that change for 6.33.0.

**Comment by mikehardy** [comment] 2020-12-17 03:13
Interesting @jhubbardsf - my error is duplicate symbols, so I think it's different. "they do this in later versions" - do you know what version you first saw it? If it's fixed in later versions I'm inclined to leave it with the only hesitation being that react-native-firebase can use the newer v7 versions but FlutterFire can't yet - I have a forward-port pending over there to allow it but it's still rough and needs review + acceptance

**Closed** 2021-04-06 15:25 UTC
Labels: bug
