### ISSUE TITLE
Not building with Detox

### ISSUE THREAD

**Issue by rborn** [invertase/firestore-ios-sdk-frameworks#15] opened 2020-10-15 07:51 UTC
Hi 

I'm trying to use this with detox but I get a lot of errors when building, starting with 

```
/....../app/letsemjoyapp/node_modules/@react-native-firebase/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.h:26:4: expected a type

+ (FIRFirestore *)getFirestoreForApp:(FIRApp *)firebaseApp;
^

```

My Detox build command is 

```
xcodebuild -workspace ios/emjoy.xcworkspace -UseNewBuildSystem=NO -scheme emjoy -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build | xcpretty
````

Any idea ? 😻

**Comment by mikehardy** [comment] 2020-10-15 14:28
I actually have the same problem when I build from Xcode (12.0.1) but it works from the command line for me?
Incidentally, 'UseNewBuildSystem=NO' why?

**Comment by rborn** [comment] 2020-10-15 15:52
@mikehardy 
My project is still set with legacy, and it doesn't build with or without that flag.
I'll check if I can remove it, but I don't think it will make any difference.

**Comment by mikehardy** [comment] 2020-10-15 18:41
I just reproduced this while checking on something else, detox fails while this is integrated and you build with Xcode 12.
It also won't build from Xcode even without detox, same errors.

It's fine with Xcode 11.

I welcome any suggestions...looks like it's a header path issue or something, but unfortunately I don't have the time + expertise to troubleshoot when the easy solution is to just comment that line in the Podfile (even though it means a longer build, of course)

**Comment by mikehardy** [comment] 2020-10-16 13:17
In case I wasn't explicit enough: I don't have time to solve this now but would love a solution. My best guess is something changed with regard to header search path between Xcode 11 / Xcode 12 and something in the podspec needs a tweak

If I had time I'd open Xcode after attempting integration, reproduce the failure, then find the headers on disk via Terminal and trial and error where to put them, and it would be terrible and slow because I am terrible and slow at Objective-C and Xcode... thus the 🙏  for a PR

**Comment by rborn** [comment] 2020-10-16 17:40
I'm in the same boat, just disabled it for now, will try to see if I can fix (my objC-fu is veeeery rusty 😅 )

**Comment by mikehardy** [comment] 2020-10-16 17:46
on the plus side for reproduction I saw the exact same messages just compiling my work project with it integrated in Xcode 12, no detox needed. So it should be glaringly obvious and if I had any Obj-C fu it'd be fixed already haha

**Comment by rborn** [comment] 2020-10-29 08:32
@mikehardy I've updated the rnfirebase/app to `8.4.6` , the precompiled sdk to `6.34.0` , Xcode to `12.1` and it seems to compile fine  now with xcode (detox). I didn't make a release yet but I'll let you know when I do.

**Comment by mikehardy** [comment] 2020-10-29 11:04
That's great news. I'm guessing 12.1 was the trick then as I already had the others I think. I have one machine still 12.0 and one 12.1 so I can confirm that later. Thanks for the report!

**Comment by mikehardy** [comment] 2020-10-30 01:45
I confirm 12.1 works with this enabled and Detox. I no longer have problems using the framework, I'm going to happily close this. It was a 12.0 thing

**Closed by mikehardy** 2020-10-30 01:45 UTC
